export const summaryData = {
  statusCode: 0,
  statusLookupKey: "com.techsavy.general.success",
  statusDescription: "Success",
  data: {
    ticketsSummary: [
      {
        id: "Lowest",
        companyId: 0,
        name: "Lowest",
        quantity: 5,
        lineItemTotal: 125.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
      {
        id: "General",
        companyId: 0,
        name: "General",
        quantity: 4,
        lineItemTotal: 200.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
      {
        id: "VIP",
        companyId: 0,
        name: "VIP",
        quantity: 3,
        lineItemTotal: 225.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
      {
        id: "VVIP",
        companyId: 0,
        name: "VVIP",
        quantity: 2,
        lineItemTotal: 200.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
    ],
    boothsSummary: [
      {
        id: "Small",
        companyId: 0,
        name: "Small",
        quantity: 4,
        lineItemTotal: 100.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
      {
        id: "Medium",
        companyId: 0,
        name: "Medium",
        quantity: 3,
        lineItemTotal: 150.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
      {
        id: "Large",
        companyId: 0,
        name: "Large",
        quantity: 2,
        lineItemTotal: 150.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
      {
        id: "XL Booth",
        companyId: 0,
        name: "XL Booth",
        quantity: 1,
        lineItemTotal: 100.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
    ],
    sponsorsSummary: [
      {
        id: "Silver",
        companyId: 0,
        name: "Silver",
        quantity: 3,
        lineItemTotal: 75.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
      {
        id: "Gold",
        companyId: 0,
        name: "Gold",
        quantity: 3,
        lineItemTotal: 150.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
      {
        id: "Platinum",
        companyId: 0,
        name: "Platinum",
        quantity: 2,
        lineItemTotal: 150.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
      {
        id: "Diamond",
        companyId: 0,
        name: "Diamond",
        quantity: 1,
        lineItemTotal: 100.0,
        type: "Ticket",
        groupDiscountCount: 0,
        groupDiscountPercentage: 0.0,
        groupDiscountPricePerTicket: 0.0,
      },
    ],
  },
  messages: [],
  success: true,
};
